--Problem 1
USE ships

SELECT 
	c.CLASS,
	SUM(CASE WHEN DISPLACEMENT > 30000 THEN 1 ELSE 0 END) AS [Big Ships],
	COUNT(o.SHIP) AS [Victory Ships],
	SUM(CASE WHEN LAUNCHED > 1942 THEN 1 ELSE 0 END) AS [New Ships]
FROM CLASSES c
JOIN SHIPS s ON c.CLASS = s.CLASS
LEFT JOIN (SELECT DISTINCT SHIP FROM OUTCOMES WHERE RESULT = 'ok') o
	ON NAME = o.SHIP
GROUP BY c.CLASS
HAVING COUNT(DISTINCT LAUNCHED) >= 3

--Problem 2
USE pc
BEGIN TRAN

UPDATE pc
SET price = price + 10
WHERE ram > ALL(
	SELECT ram 
	FROM laptop l 
	WHERE l.PRICE >= ALL(SELECT PRICE FROM laptop WHERE screen = 14)
		AND screen = 14
)

ROLLBACK

--Problem 3
USE ships

GO
CREATE VIEW prob3
AS
	SELECT 
		s.NAME, 
		c.CLASS, 
		BATTLE, 
		(SELECT COUNT(DISTINCT NAME) 
			FROM SHIPS s1
			JOIN CLASSES c1 ON s1.CLASS = c1.CLASS
			JOIN OUTCOMES ON NAME = SHIP
			WHERE NUMGUNS > 8 AND BATTLE = o.BATTLE
		) AS [Ships in Battle],
		LAUNCHED,
		YEAR(DATE) AS [Year of Battle]
	FROM SHIPS s
	JOIN CLASSES c ON s.CLASS = c.CLASS
	JOIN OUTCOMES o ON NAME = SHIP
	JOIN BATTLES b ON BATTLE = b.NAME
	WHERE NUMGUNS > 8
GO

--Problem 4
USE ships

GO
CREATE TRIGGER tr4
ON OUTCOMES
AFTER INSERT, UPDATE
AS
BEGIN
	IF EXISTS(
		SELECT 1
		FROM inserted i
		JOIN BATTLES b ON i.BATTLE = b.NAME
		JOIN SHIPS s ON i.SHIP = s.NAME
		JOIN CLASSES c ON s.CLASS = c.CLASS
		WHERE YEAR(DATE) > 1941 AND NUMGUNS < 10
	)
	BEGIN
		ROLLBACK
		RAISERROR('Data integrity violation', 16, 1)
	END
END
GO

DROP trigger tr4