-- 1. Movies
USE movies

SELECT ADDRESS FROM STUDIO WHERE NAME = 'MGM'
SELECT BIRTHDATE FROM MOVIESTAR WHERE NAME = 'Sandra Bullock'
SELECT STARNAME FROM STARSIN WHERE MOVIEYEAR = 1980 AND MOVIETITLE LIKE '%Empire%'
SELECT NAME FROM MOVIEEXEC WHERE NETWORTH > 10000000
SELECT NAME FROM MOVIESTAR WHERE GENDER = 'M' OR ADDRESS LIKE '%MaLIBU%'

-- 2. PC
USE pc

SELECT CODE, SPEED AS MHz, HD AS GB FROM PC WHERE PRICE < 1200

SELECT MODEL, ROUND(PRICE / 1.1, 2) AS 'PRICE EURO'
FROM LAPTOP
ORDER BY PRICE ASC

SELECT MODEL, RAM, SCREEN
FROM LAPTOP WHERE PRICE > 1000

SELECT * FROM PRINTER
WHERE COLOR = 'y'

SELECT MODEL, SPEED, HD
FROM PC
WHERE (CD = '12x' OR CD = '16x') AND PRICE < 2000

SELECT CODE, MODEL, (SPEED + RAM + 10 * SCREEN) AS RATING
FROM LAPTOP
ORDER BY RATING DESC, CODE

-- 3. Ships
USE ships

SELECT CLASS, COUNTRY
FROM CLASSES
WHERE NUMGUNS < 10

SELECT NAME FROM SHIPS
WHERE YEAR(LAUNCHED) < 1918

SELECT SHIP FROM OUTCOMES
WHERE RESULT = 'sunk'

SELECT NAME FROM SHIPS
WHERE NAME = CLASS

SELECT NAME FROM SHIPS WHERE NAME LIKE 'R%'

SELECT NAME FROM SHIPS WHERE LEN(NAME) - LEN(REPLACE(NAME,' ','')) = 1