USE mods

--Problem 1

DELETE FROM MOVIE
WHERE TITLE = 'Star Trek: Nemesis' OR TITLE = 'Star Trek'

ALTER TABLE MOVIE
ADD CONSTRAINT UQ_MOVIE_LENGTH UNIQUE(LENGTH)

ALTER TABLE MOVIE
ADD CONSTRAINT UQ_MOVIE_STUDIO_LENGTH UNIQUE(STUDIONAME, LENGTH)

--Problem 2

ALTER TABLE MOVIE
DROP CONSTRAINT UQ_MOVIE_LENGTH

ALTER TABLE MOVIE
DROP CONSTRAINT UQ_MOVIE_STUDIO_LENGTH

INSERT INTO MOVIE
VALUES ('Star Trek: Nemesis', 2002, 116, 'Y', 'Paramount', 123),
	   ('Star Trek', 1979, 132, 'Y', 'Paramount', 222)

--Problem 3
CREATE TABLE Students(
	fn INT PRIMARY KEY NOT NULL CHECK (fn >= 0 AND fn < 100000),
	name VARCHAR(100) NOT NULL,
	ucn CHAR(10) UNIQUE NOT NULL,
	email VARCHAR(100) UNIQUE NOT NULL,
	birthdate DATE NOT NULL,
	admission_date DATE NOT NULL,
	CHECK (admission_date >= DATEADD(year, 18, birthdate))
)

ALTER TABLE Students
ADD CONSTRAINT CK_EMAIL CHECK (email LIKE '%@%.%')

CREATE TABLE Courses(
	id INT PRIMARY KEY,
	name VARCHAR(100)
)

CREATE TABLE StudentCourses(
	student_fn INT FOREIGN KEY REFERENCES Students(fn),
	course_id INT FOREIGN KEY REFERENCES Courses(id) ON DELETE CASCADE
)