USE pazhev
--Problem 1

SELECT CASE 
		WHEN YEAR(BIRTHDATE) < 1960 THEN '50s and before'
		WHEN YEAR(BIRTHDATE) < 1970 THEN '60s'
		WHEN YEAR(BIRTHDATE) < 1980 THEN '70s'
		ELSE '80s and after'
	END AS 'Period', COUNT(*) AS COUNT
FROM MOVIESTAR
GROUP BY CASE 
		WHEN YEAR(BIRTHDATE) < 1960 THEN '50s and before'
		WHEN YEAR(BIRTHDATE) < 1970 THEN '60s'
		WHEN YEAR(BIRTHDATE) < 1980 THEN '70s'
		ELSE '80s and after'
	END

--Problem 2

SELECT BATTLE
FROM OUTCOMES
JOIN SHIPS s ON SHIP = NAME
JOIN CLASSES c ON c.CLASS = s.CLASS
WHERE NUMGUNS < 9
GROUP BY BATTLE
HAVING COUNT(SHIP) >= 3
	AND SUM(CASE WHEN RESULT = 'ok' THEN 1 ELSE 0 END) >= 2

--Problem 3

SELECT BATTLE, COUNT(DISTINCT SHIP)
FROM OUTCOMES
JOIN SHIPS s ON NAME = SHIP
JOIN CLASSES c ON s.CLASS = c.CLASS
WHERE COUNTRY = 'USA' AND RESULT = 'sunk'
GROUP BY BATTLE

SELECT DISTINCT BATTLE
FROM OUTCOMES o
JOIN SHIPS s ON NAME = SHIP
JOIN CLASSES c ON s.CLASS = c.CLASS
GROUP BY BATTLE, COUNTRY
HAVING COUNT(*) >= 3

SELECT CLASS
FROM SHIPS
GROUP BY CLASS
HAVING MAX(LAUNCHED) <= 1921

SELECT NAME, COUNT(RESULT)
FROM SHIPS
LEFT JOIN OUTCOMES ON NAME = SHIP AND RESULT = 'damaged'
GROUP BY NAME

SELECT COUNTRY, COUNT(DISTINCT NAME), COUNT(RESULT)
FROM CLASSES c
LEFT JOIN SHIPS s ON c.CLASS = s.CLASS
LEFT JOIN OUTCOMES ON NAME = SHIP AND RESULT = 'sunk'
GROUP BY COUNTRY

SELECT COUNTRY, COUNT(DISTINCT o1.SHIP), COUNT(DISTINCT o2.SHIP)
FROM CLASSES c
LEFT JOIN SHIPS s ON c.CLASS = s.CLASS
LEFT JOIN OUTCOMES o1 ON NAME = o1.SHIP AND o1.RESULT = 'damaged'
LEFT JOIN OUTCOMES o2 ON NAME = o2.SHIP AND o2.RESULT = 'sunk'
GROUP BY COUNTRY

SELECT CLASS, COUNT(DISTINCT SHIP)
FROM SHIPS
LEFT JOIN OUTCOMES ON NAME = SHIP AND RESULT = 'ok'
GROUP BY CLASS
HAVING COUNT(DISTINCT NAME) >= 3

SELECT NAME, BIRTHDATE, (SELECT TOP 1 STUDIONAME 
						FROM MOVIE 
						JOIN STARSIN ON MOVIETITLE = TITLE AND MOVIEYEAR = YEAR 
						WHERE STARNAME = NAME
						GROUP BY STUDIONAME
						ORDER BY COUNT(*) DESC)
FROM MOVIESTAR

USE pc

SELECT maker, (SELECT COUNT(*) FROM product p JOIN pc ON p.model = pc.model WHERE p.maker = pro.maker)
FROM product pro
JOIN printer pri ON pro.model = pri.model
WHERE pri.type = 'Laser'
GROUP BY maker
HAVING COUNT(*) >= 2

SELECT maker
FROM product p
LEFT JOIN pc ON p.model = pc.model
LEFT JOIN laptop l ON p.model = l.model
GROUP BY maker
HAVING AVG(pc.price) < AVG(l.price)

SELECT p.model
FROM product p
JOIN pc ON p.model = pc.model
GROUP BY p.model, p.maker
HAVING AVG(price) < (SELECT MIN(price) 
					FROM product p2 
					JOIN laptop l ON p2.model = l.model 
					WHERE p2.maker = p.maker)

USE pazhev

SELECT DISTINCT TITLE, YEAR
FROM MOVIE
JOIN STARSIN ON TITLE = MOVIETITLE AND YEAR = MOVIEYEAR
WHERE YEAR < 1982 AND STARNAME NOT LIKE '%k%' AND STARNAME NOT LIKE '%b%'
ORDER BY YEAR ASC

SELECT m1.TITLE, m1.LENGTH / 60
FROM MOVIE m1
JOIN MOVIE m2 ON m2.TITLE = 'Terms of Endearment'
WHERE m1.YEAR = m2.YEAR AND m1.LENGTH IS NULL OR m1.LENGTH < m2.LENGTH

SELECT NAME
FROM MOVIEEXEC
WHERE NAME IN (SELECT STARNAME FROM STARSIN WHERE MOVIEYEAR < 1980)
	AND NAME IN (SELECT STARNAME FROM STARSIN WHERE MOVIEYEAR > 1985)

SELECT *
FROM MOVIE m
WHERE INCOLOR = 'n' AND YEAR < (SELECT MIN(YEAR) FROM MOVIE WHERE INCOLOR = 'y' AND STUDIONAME = m.STUDIONAME)

SELECT NAME, ADDRESS
FROM STUDIO
LEFT JOIN MOVIE ON NAME = STUDIONAME
LEFT JOIN STARSIN ON TITLE = MOVIETITLE AND YEAR = MOVIEYEAR
GROUP BY NAME, ADDRESS
HAVING COUNT(DISTINCT STARNAME) < 5
ORDER BY COUNT(DISTINCT STARNAME) DESC

SELECT NAME, LAUNCHED
FROM SHIPS
WHERE CLASS NOT LIKE '%i%' AND CLASS NOT LIKE '%k%'
ORDER BY LAUNCHED DESC

SELECT DISTINCT BATTLE
FROM OUTCOMES
JOIN SHIPS s ON SHIP = NAME
JOIN CLASSES c ON s.CLASS = c.CLASS
WHERE COUNTRY = 'Japan' AND RESULT = 'damaged'

SELECT NAME, s.CLASS
FROM SHIPS s
JOIN CLASSES c ON s.CLASS = c.CLASS
WHERE LAUNCHED = 1 + (SELECT LAUNCHED FROM SHIPS WHERE NAME = 'Rodney')
	AND NUMGUNS > (SELECT AVG(NUMGUNS) FROM CLASSES WHERE COUNTRY = c.COUNTRY)

SELECT CLASS
FROM CLASSES c
WHERE COUNTRY = 'USA' AND (SELECT MAX(LAUNCHED) - MIN(LAUNCHED) FROM SHIPS WHERE CLASS = c.CLASS) >= 10

SELECT NAME, AVG(COUNT)
FROM (SELECT b.NAME, COUNT(DISTINCT s.NAME) AS COUNT
	FROM BATTLES b
	LEFT JOIN OUTCOMES ON b.NAME = BATTLE
	LEFT JOIN SHIPS s ON SHIP = s.NAME
	LEFT JOIN CLASSES c ON s.CLASS = c.CLASS
	GROUP BY b.NAME, COUNTRY) AS sc
GROUP BY NAME

SELECT COUNTRY, COUNT(DISTINCT NAME), COUNT(DISTINCT o1.BATTLE), COUNT(DISTINCT o2.BATTLE)
FROM CLASSES c
LEFT JOIN SHIPS s ON c.CLASS = s.CLASS
LEFT JOIN OUTCOMES o1 ON NAME = o1.SHIP
LEFT JOIN OUTCOMES o2 ON NAME = o2.SHIP AND o2.RESULT = 'sunk'
GROUP BY COUNTRY

SELECT NAME, COUNT(DISTINCT STUDIONAME)
FROM MOVIESTAR
JOIN STARSIN ON NAME = STARNAME
JOIN MOVIE ON MOVIETITLE = TITLE AND MOVIEYEAR = YEAR
GROUP BY NAME

SELECT NAME, COUNT(DISTINCT STUDIONAME)
FROM MOVIESTAR
LEFT JOIN STARSIN ON NAME = STARNAME
LEFT JOIN MOVIE ON MOVIETITLE = TITLE AND MOVIEYEAR = YEAR
GROUP BY NAME

SELECT STARNAME
FROM STARSIN
WHERE MOVIEYEAR > 1990
GROUP BY STARNAME
HAVING COUNT(*) >= 3

USE pc

SELECT model
FROM pc
GROUP BY model
ORDER BY MAX(price) 