-- Problem 1
USE movies

SELECT NAME
FROM MOVIESTAR
JOIN STARSIN ON NAME = STARNAME
WHERE MOVIETITLE = 'Terms of Endearment' AND GENDER = 'F'

SELECT STARNAME
FROM STARSIN
JOIN MOVIE ON MOVIETITLE = TITLE
WHERE MOVIEYEAR = 1995 AND STUDIONAME = 'MGM'

-- Problem 2
USE pc

SELECT MAKER, SPEED
FROM LAPTOP
JOIN PRODUCT ON LAPTOP.MODEL = PRODUCT.MODEL
WHERE HD >= 9

SELECT MODEL, PRICE FROM
((SELECT PRODUCT.MODEL, PRICE, MAKER
FROM PRODUCT
JOIN LAPTOP ON LAPTOP.MODEL = PRODUCT.MODEL)
UNION
(SELECT  PRODUCT.MODEL, PRICE, MAKER
FROM PRODUCT
JOIN PC ON PC.MODEL = PRODUCT.MODEL)
UNION
(SELECT PRODUCT.MODEL, PRICE, MAKER
FROM PRODUCT
JOIN PRINTER ON PRINTER.MODEL = PRODUCT.MODEL))
AS T
WHERE MAKER = 'B'
ORDER BY PRICE DESC

SELECT DISTINCT pc1.HD
FROM PC pc1
JOIN PC pc2 ON pc1.CODE != pc2.CODE
WHERE pc2.HD = pc1.HD

SELECT pc1.MODEL, pc2.MODEL
FROM PC pc1
JOIN PC pc2 ON pc1.SPEED = pc2.SPEED AND pc1.RAM = pc2.RAM AND pc1.MODEL < pc2.MODEL

SELECT DISTINCT p1.MAKER
FROM PC pc1
JOIN PC pc2 ON pc1.CODE != pc2.CODE
JOIN PRODUCT p1 ON pc1.MODEL = p1.MODEL
JOIN PRODUCT p2 ON pc2.MODEL = p2.MODEL
WHERE pc1.SPEED >= 500 AND pc2.SPEED >= 500 AND p1.MAKER = p2.MAKER

-- Problem 3
USE ships

SELECT NAME
FROM SHIPS s
JOIN CLASSES c ON s.CLASS = c.CLASS
WHERE DISPLACEMENT > 35000

SELECT NAME, DISPLACEMENT, NUMGUNS
FROM SHIPS s
JOIN CLASSES c ON s.CLASS = c.CLASS
JOIN OUTCOMES o ON SHIP = NAME
WHERE BATTLE = 'Guadalcanal'

SELECT DISTINCT c1.COUNTRY
FROM CLASSES c1
JOIN CLASSES c2 ON c1.CLASS != c2.CLASS
WHERE c1.COUNTRY = c2.COUNTRY AND c1.TYPE = 'bb' AND c2.TYPE = 'bc'

SELECT s.NAME
FROM SHIPS s
JOIN OUTCOMES o1 ON o1.SHIP = s.NAME
JOIN BATTLES b1 ON o1.BATTLE = b1.NAME
JOIN OUTCOMES o2 ON o2.SHIP = s.NAME
JOIN BATTLES b2 ON o2.BATTLE = b2.NAME
WHERE b1.DATE < b2.DATE AND o1.RESULT = 'damaged'
