-- Problem 1
USE pc

SELECT AVG(SPEED) AS [Average Speed]
FROM PC

SELECT MAKER, AVG(SCREEN) AS [Average Laptop Screen]
FROM PRODUCT p
LEFT JOIN LAPTOP l ON p.MODEL = l.MODEL
GROUP BY MAKER

SELECT AVG(SPEED) AS [Average Speed]
FROM LAPTOP
WHERE PRICE > 1000

SELECT AVG(PRICE) AS [Average Price]
FROM PC
JOIN PRODUCT p ON PC.MODEL = p.MODEL
WHERE MAKER = 'A'

SELECT AVG(PRICE) AS [Average Price]
FROM (
	(SELECT PRICE, MODEL FROM PC) 
	UNION 
	(SELECT PRICE, MODEL FROM LAPTOP)
) c
JOIN PRODUCT p ON c.MODEL = p.MODEL
WHERE MAKER = 'B'

SELECT SPEED, AVG(PRICE) AS [Average Price]
FROM PC
GROUP BY SPEED

SELECT MAKER
FROM PRODUCT p
JOIN PC ON p.MODEL = PC.MODEL
GROUP BY MAKER
HAVING COUNT(DISTINCT p.MODEL) >= 3

SELECT DISTINCT MAKER
FROM PRODUCT p
JOIN PC ON p.MODEL = PC.MODEL
WHERE PRICE = (SELECT MAX(PRICE) FROM PC)

SELECT SPEED, AVG(PRICE) AS [Average Price]
FROM PC
GROUP BY SPEED
HAVING SPEED > 800

SELECT AVG(HD) AS [Average Storage]
FROM PC
JOIN PRODUCT p ON PC.MODEL = p.MODEL
WHERE MAKER IN (SELECT MAKER FROM PRODUCT WHERE TYPE = 'Printer')

SELECT MAX(PRICE) - MIN(PRICE) AS [Price Difference]
FROM LAPTOP
GROUP BY SCREEN

-- Problem 2
USE ships

SELECT COUNT(*) FROM CLASSES

SELECT AVG(NUMGUNS)
FROM SHIPS s
JOIN CLASSES c ON s.CLASS = c.CLASS

SELECT c.CLASS, MIN(LAUNCHED) AS [First Year], MAX(LAUNCHED) AS [Last Year]
FROM CLASSES c
LEFT JOIN SHIPS s ON c.CLASS = s.CLASS
GROUP BY c.CLASS

SELECT c.CLASS, SUM(CASE RESULT WHEN 'sunk' THEN 1 ELSE 0 END) AS [Sunk Ships]
FROM CLASSES c
LEFT JOIN SHIPS s ON c.CLASS = s.CLASS
LEFT JOIN OUTCOMES o ON NAME = SHIP
GROUP BY c.CLASS

SELECT c.CLASS, SUM(CASE RESULT WHEN 'sunk' THEN 1 ELSE 0 END) AS [Sunk Ships]
FROM CLASSES c
JOIN SHIPS s ON c.CLASS = s.CLASS
LEFT JOIN OUTCOMES ON NAME = SHIP
GROUP BY c.CLASS
HAVING COUNT(DISTINCT NAME) > 4

SELECT COUNTRY, AVG(DISPLACEMENT)
FROM CLASSES --c JOIN SHIPS s ON c.CLASS = s.CLASS
GROUP BY COUNTRY

-- Problem 3
USE movies

SELECT STARNAME, COUNT(DISTINCT STUDIONAME) AS [Studios]
FROM STARSIN
JOIN MOVIE ON MOVIETITLE = TITLE AND MOVIEYEAR = YEAR
GROUP BY STARNAME

SELECT NAME, COUNT(DISTINCT STUDIONAME) AS [Studios]
FROM MOVIESTAR
LEFT JOIN STARSIN ON NAME = STARNAME
LEFT JOIN MOVIE ON MOVIETITLE = TITLE AND MOVIEYEAR = YEAR
GROUP BY NAME

SELECT STARNAME
FROM STARSIN
WHERE MOVIEYEAR > 1990
GROUP BY STARNAME
HAVING COUNT(*) >= 3

USE pc

SELECT MODEL
FROM PC
GROUP BY MODEL
ORDER BY MAX(PRICE)