--Problem 1

--allows modification
CREATE VIEW actresses
AS
	SELECT NAME, BIRTHDATE
	FROM MOVIESTAR
	WHERE GENDER = 'F'
GO

--doesn't allow modification
CREATE VIEW actorMovieCount
AS
	SELECT NAME, COUNT(MOVIETITLE) AS MOVIESCOUNT
	FROM MOVIESTAR
	LEFT JOIN STARSIN ON NAME = STARNAME
	GROUP BY NAME
GO

-- Problem 2
CREATE VIEW allProducts
AS
	(SELECT CODE, MODEL, PRICE FROM PC)
	UNION
	(SELECT CODE, MODEL, PRICE FROM LAPTOP)
	UNION
	(SELECT CODE, MODEL, PRICE FROM PRINTER)
GO

ALTER VIEW allProducts
AS
	(SELECT CODE, MODEL, PRICE, 'PC' AS TYPE FROM PC)
	UNION
	(SELECT CODE, MODEL, PRICE, 'Laptop' AS TYPE FROM LAPTOP)
	UNION
	(SELECT CODE, MODEL, PRICE, 'Printer' AS TYPE FROM PRINTER)
GO

ALTER VIEW allProducts
AS
	(SELECT CODE, MODEL, PRICE, 'PC' AS TYPE, SPEED FROM PC)
	UNION
	(SELECT CODE, MODEL, PRICE, 'Laptop' AS TYPE, SPEED FROM LAPTOP)
	UNION
	(SELECT CODE, MODEL, PRICE, 'Printer' AS TYPE, NULL AS SPEED FROM PRINTER)
GO

--Problem 3
CREATE VIEW BritishShips
AS
	SELECT NAME, s.CLASS, TYPE, NUMGUNS, BORE, DISPLACEMENT, LAUNCHED
	FROM SHIPS s
	JOIN CLASSES c ON s.CLASS = c.CLASS
	WHERE COUNTRY = 'Gt.Britain'
GO

SELECT NUMGUNS, DISPLACEMENT
FROM BritishShips
WHERE TYPE = 'bb' AND LAUNCHED < 1919

SELECT NUMGUNS, DISPLACEMENT
FROM SHIPS s
JOIN CLASSES c ON s.CLASS = c.CLASS
WHERE COUNTRY = 'Gt.Britain' AND TYPE = 'bb' AND LAUNCHED < 1919
GO

CREATE VIEW AvgDisplacement
AS
	SELECT COUNTRY, AVG(DISPLACEMENT) AS [Average Displacement]
	FROM CLASSES
	GROUP BY COUNTRY
GO

CREATE OR ALTER VIEW SunkenShips
AS
	SELECT SHIP, BATTLE
	FROM OUTCOMES
	WHERE RESULT = 'sunk'
GO

ALTER TABLE OUTCOMES
ADD DEFAULT 'sunk' FOR RESULT

INSERT INTO SunkenShips
VALUES ('California', 'Guadalcanal')

SELECT * FROM SunkenShips
GO

CREATE VIEW ManyGuns
AS
	SELECT *
	FROM CLASSES
	WHERE NUMGUNS >= 9
WITH CHECK OPTION
GO

UPDATE ManyGuns
SET NUMGUNS = 15
WHERE CLASS = 'Iowa'

UPDATE ManyGuns
SET NUMGUNS = 5
WHERE CLASS = 'Iowa'
GO

ALTER VIEW ManyGuns
AS
	SELECT *
	FROM CLASSES
	WHERE NUMGUNS >= 9
GO

CREATE VIEW DamagedBattles
AS
	SELECT BATTLE
	FROM OUTCOMES
	JOIN SHIPS ON SHIP = NAME
	WHERE CLASS NOT IN (SELECT CLASS FROM ManyGuns)
	GROUP BY BATTLE
	HAVING COUNT(SHIP) >= 3 AND COUNT(CASE WHEN RESULT = 'damaged' THEN 1 END) > 0
GO