-- Problem 1
USE movies

SELECT DISTINCT STUDIONAME, STARNAME
FROM MOVIE
JOIN STARSIN ON TITLE = MOVIETITLE AND YEAR = MOVIEYEAR
ORDER BY STUDIONAME

SELECT DISTINCT NAME
FROM MOVIEEXEC
JOIN MOVIE ON CERT# = PRODUCERC#
JOIN STARSIN ON TITLE = MOVIETITLE AND YEAR = MOVIEYEAR
WHERE STARNAME = 'Harrison Ford'

SELECT NAME
FROM MOVIESTAR
JOIN STARSIN ON NAME = STARNAME
JOIN MOVIE ON TITLE = MOVIETITLE AND YEAR = MOVIEYEAR
WHERE STUDIONAME = 'MGM' AND GENDER = 'F'

SELECT NAME, m2.TITLE
FROM MOVIEEXEC
JOIN MOVIE m1 ON m1.PRODUCERC# = CERT#
JOIN MOVIE m2 ON m1.PRODUCERC# = CERT#
WHERE m1.TITLE = 'Star Wars'

SELECT TITLE, YEAR, NAME
FROM MOVIE
LEFT JOIN MOVIEEXEC ON PRODUCERC# = CERT#

SELECT TITLE, YEAR, me.NAME, STUDIONAME, s.ADDRESS
FROM MOVIE
LEFT JOIN MOVIEEXEC me ON PRODUCERC# = CERT#
LEFT JOIN STUDIO s ON STUDIONAME = s.NAME

SELECT NAME
FROM MOVIESTAR
LEFT JOIN STARSIN ON STARNAME = NAME
WHERE MOVIETITLE IS NULL

-- Problem 2
USE pc

SELECT DISTINCT p.MODEL, PRICE
FROM PRODUCT p
LEFT JOIN PC ON p.MODEL = PC.MODEL
WHERE TYPE = 'PC'

SELECT MAKER, p.MODEL, p.TYPE
FROM PRODUCT p
LEFT JOIN PC ON p.MODEL = PC.MODEL
LEFT JOIN LAPTOP l ON p.MODEL = l.MODEL
LEFT JOIN PRINTER pr ON p.MODEL = pr.MODEL
WHERE PC.CODE IS NULL AND l.CODE IS NULL AND pr.CODE IS NULL

-- Problem 3
USE ships

SELECT NAME, COUNTRY, NUMGUNS, LAUNCHED
FROM SHIPS s
JOIN CLASSES c ON s.CLASS = c.CLASS

SELECT DISTINCT SHIP
FROM OUTCOMES
JOIN BATTLES ON BATTLE = NAME
WHERE YEAR(DATE) = 1942

-- Problem 4
USE ships

SELECT NAME, LAUNCHED
FROM SHIPS
WHERE NAME = CLASS

USE movies

SELECT *
FROM MOVIE
WHERE TITLE LIKE '%Star%' AND TITLE LIKE '%Trek%'
ORDER BY YEAR ASC, TITLE

SELECT DISTINCT MOVIETITLE, MOVIEYEAR
FROM STARSIN
JOIN MOVIESTAR ON NAME = STARNAME
WHERE BIRTHDATE BETWEEN '1970-01-01' AND '1980-07-01'

USE ships

SELECT DISTINCT SHIP
FROM OUTCOMES
WHERE SHIP LIKE 'C%' OR SHIP LIKE 'K%'

SELECT DISTINCT COUNTRY
FROM CLASSES c
JOIN SHIPS s ON c.CLASS = s.CLASS
JOIN OUTCOMES o ON NAME = SHIP
WHERE RESULT = 'sunk'

SELECT DISTINCT COUNTRY
FROM CLASSES c
WHERE COUNTRY NOT IN 
	(SELECT DISTINCT COUNTRY
	FROM CLASSES c
	JOIN SHIPS s ON c.CLASS = s.CLASS
	JOIN OUTCOMES o ON NAME = SHIP
	WHERE RESULT = 'sunk')

SELECT c.CLASS
FROM CLASSES c
LEFT JOIN SHIPS s ON s.CLASS = c.CLASS AND LAUNCHED > 1921
WHERE LAUNCHED IS NULL

SELECT CLASS, COUNTRY, BORE * 2.54 AS BORE
FROM CLASSES
WHERE NUMGUNS IN (6, 8, 10)

SELECT DISTINCT c1.COUNTRY
FROM CLASSES c1
JOIN CLASSES c2 ON c1.COUNTRY = c2.COUNTRY
WHERE c1.BORE < c2.BORE

SELECT DISTINCT COUNTRY
FROM CLASSES
WHERE NUMGUNS >= ALL(SELECT NUMGUNS FROM CLASSES)

USE pc

SELECT *
FROM PC
JOIN PRODUCT p ON PC.MODEL = p.MODEL
WHERE PRICE <= ALL(SELECT PRICE FROM LAPTOP l JOIN PRODUCT pr ON l.MODEL = pr.MODEL WHERE pr.MAKER = p.MAKER)

SELECT *
FROM PC
JOIN PRODUCT p ON PC.MODEL = p.MODEL
WHERE PRICE <= ALL(
	(SELECT PRICE 
	FROM LAPTOP l 
	JOIN PRODUCT pr ON l.MODEL = pr.MODEL 
	WHERE pr.MAKER = p.MAKER)
	UNION
	(SELECT PRICE 
	FROM PRINTER 
	JOIN PRODUCT ON PRINTER.MODEL = PRODUCT.MODEL 
	WHERE PRODUCT.MAKER = p.MAKER)
)
