USE mods

BEGIN TRANSACTION

--Problem 1

INSERT INTO MOVIESTAR(NAME, GENDER, BIRTHDATE)
VALUES ('Nicole Kidman', 'F', '1967-06-20')

DELETE FROM MOVIEEXEC
WHERE NETWORTH < 10000000

DELETE FROM MOVIESTAR
WHERE ADDRESS IS NULL

UPDATE MOVIEEXEC
SET NAME = 'Pres. ' + NAME
WHERE CERT# IN (SELECT PRESC# FROM STUDIO)

--Problem 2
INSERT INTO PRODUCT
VALUES ('C', '1100', 'PC')

INSERT INTO PC
VALUES (12, '1100', 2400, 2048, 500, '52x', 299)

DELETE FROM PC
WHERE MODEL = '1100'

DELETE FROM PRODUCT
WHERE MODEL = '1100' AND TYPE = 'PC'

INSERT INTO LAPTOP
SELECT CODE + 100, MODEL, SPEED, RAM, HD, PRICE + 500, 15
FROM PC

DELETE FROM LAPTOP
WHERE MODEL IN (
	SELECT MODEL 
	FROM PRODUCT 
	WHERE MAKER NOT IN (SELECT MAKER FROM PRODUCT WHERE TYPE = 'Printer')
) 

UPDATE PRODUCT
SET MAKER = 'A'
WHERE MAKER = 'B'

UPDATE PC
SET PRICE = PRICE/2, HD = HD + 20

UPDATE LAPTOP
SET SCREEN = SCREEN + 1
WHERE MODEL IN (SELECT MODEL FROM PRODUCT WHERE MAKER = 'B')

--Problem 3
INSERT INTO CLASSES(CLASS, TYPE, COUNTRY, BORE, DISPLACEMENT)
VALUES ('Nelson', 'bb', 'Gt.Britain', 16, 34000)

INSERT INTO SHIPS
VALUES ('Nelson', 'Nelson', 1927),
	   ('Nelson', 'Rodney', 1927)

DELETE FROM SHIPS
WHERE NAME IN (SELECT SHIP FROM OUTCOMES WHERE RESULT = 'sunk')

UPDATE CLASSES
SET BORE = BORE * 2.54, DISPLACEMENT = DISPLACEMENT / 1.1

DELETE c
FROM CLASSES c
WHERE (SELECT COUNT(*) FROM SHIPS s WHERE s.CLASS = c.CLASS) < 3

UPDATE c
SET BORE = b.BORE, DISPLACEMENT = b.DISPLACEMENT
FROM CLASSES c, CLASSES b
WHERE c.CLASS = 'Iowa' AND b.CLASS = 'Bismarck'

ROLLBACK TRANSACTION