--Problem 1
BEGIN TRAN
USE movies

INSERT INTO MOVIESTAR(NAME, GENDER)
VALUES ('Bruce Willis', 'M')
GO

CREATE TRIGGER tr1
ON MOVIE
AFTER INSERT
AS
	INSERT INTO STARSIN
	SELECT TITLE, YEAR, 'Bruce Willis'
	FROM inserted
	WHERE TITLE LIKE '%save%' AND TITLE LIKE '%world%'
GO

CREATE TRIGGER tr2
ON MOVIEEXEC
AFTER INSERT, UPDATE, DELETE
AS
	IF (SELECT AVG(NETWORTH) FROM MOVIEEXEC) < 500000
	BEGIN
		DELETE FROM MOVIEEXEC
		WHERE CERT# IN (SELECT CERT# FROM inserted)

		INSERT INTO MOVIEEXEC
		SELECT * FROM deleted

		RAISERROR('Average networth cannot be less than 500 000!', 15, 1)
	END
GO

CREATE OR ALTER TRIGGER tr3
ON MOVIEEXEC
INSTEAD OF DELETE
AS
	UPDATE MOVIE
	SET PRODUCERC# = NULL
	WHERE PRODUCERC# IN (SELECT CERT# FROM deleted)

	DELETE FROM MOVIEEXEC
	WHERE CERT# IN (SELECT CERT# FROM deleted)
GO

DROP TRIGGER tr1
GO

CREATE OR ALTER TRIGGER tr4
ON STARSIN
INSTEAD OF INSERT
AS
	INSERT INTO MOVIE(TITLE, YEAR)
	SELECT MOVIETITLE, MOVIEYEAR
	FROM inserted
	WHERE (SELECT COUNT(*) FROM MOVIE WHERE TITLE = MOVIETITLE AND YEAR = MOVIEYEAR) = 0
	
	INSERT INTO MOVIESTAR(NAME)
	SELECT STARNAME
	FROM inserted
	WHERE STARNAME NOT IN (SELECT NAME FROM MOVIESTAR)

	INSERT INTO STARSIN
	SELECT * FROM inserted
GO

DROP TRIGGER tr2
DROP TRIGGER tr3
DROP TRIGGER tr4
ROLLBACK

--Problem 2
USE pc
BEGIN TRAN
GO

CREATE TRIGGER tr5
ON laptop
AFTER DELETE
AS
	INSERT INTO pc
	SELECT code + 100, '1121', speed, ram, hd, '52x', price
	FROM deleted
GO

CREATE TRIGGER tr6
ON pc
INSTEAD OF UPDATE
AS
	IF UPDATE(code) 
    BEGIN
        RAISERROR('ERROR: You are not allowed to update the code. Update cancelled.', 10, 2)
    END

	DELETE FROM pc
	WHERE code IN (
		SELECT code 
		FROM inserted i
		WHERE price <= ALL(SELECT price FROM pc WHERE pc.speed = i.speed)
			AND price <= ALL(SELECT price FROM inserted i2 WHERE i2.speed = i.speed)
	)

	INSERT INTO pc
	SELECT *
	FROM inserted i
	WHERE price <= ALL(SELECT price FROM pc WHERE pc.speed = i.speed)
		AND price <= ALL(SELECT price FROM inserted i2 WHERE i2.speed = i.speed)
GO

CREATE TRIGGER tr7
ON product
INSTEAD OF INSERT, UPDATE
AS
	IF UPDATE(model) 
    BEGIN
        RAISERROR('ERROR: You are not allowed to update the model. Update cancelled.', 10, 2)
    END

	DELETE FROM product
	WHERE model IN (
		SELECT model
		FROM inserted
	)

DROP TRIGGER tr5
DROP TRIGGER tr6
ROLLBACK