-- Problem 1
USE movies

SELECT NAME
FROM MOVIESTAR
WHERE GENDER = 'F'
	AND NAME IN (SELECT NAME FROM MOVIEEXEC WHERE NETWORTH > 10000000)

SELECT NAME
FROM MOVIESTAR
WHERE NAME NOT IN (SELECT NAME FROM MOVIEEXEC)

-- Problem 2
USE pc

SELECT DISTINCT MAKER
FROM PRODUCT
WHERE MODEL IN (SELECT MODEL FROM PC WHERE SPEED >= 500)

SELECT *
FROM LAPTOP
WHERE SPEED < ALL(SELECT SPEED FROM PC)

SELECT p.MODEL
FROM PRODUCT p
JOIN ((SELECT MODEL, PRICE FROM PC)
	UNION
	(SELECT MODEL, PRICE FROM LAPTOP)
	UNION
	(SELECT MODEL, PRICE FROM PRINTER)) plp ON p.MODEL = plp.MODEL
WHERE PRICE >= ALL((SELECT PRICE FROM PC)
	UNION
	(SELECT PRICE FROM LAPTOP)
	UNION
	(SELECT PRICE FROM PRINTER))

SELECT DISTINCT MAKER
FROM PRODUCT
WHERE MODEL IN (SELECT MODEL FROM PRINTER WHERE COLOR = 'y' 
	AND PRICE <= ALL(SELECT PRICE FROM PRINTER WHERE COLOR = 'y'))

SELECT DISTINCT MAKER
FROM PRODUCT
WHERE MODEL IN (
	SELECT MODEL 
	FROM PC 
	WHERE RAM <= ALL(SELECT RAM FROM PC) 
		AND SPEED >= ALL(SELECT SPEED FROM PC WHERE RAM <= ALL(SELECT RAM FROM PC))
)

-- Problem 3
USE ships

SELECT DISTINCT COUNTRY
FROM CLASSES
WHERE NUMGUNS >= ALL(SELECT NUMGUNS FROM CLASSES)

SELECT NAME
FROM SHIPS
WHERE CLASS IN (SELECT CLASS FROM CLASSES WHERE BORE = 16)

SELECT BATTLE
FROM OUTCOMES
WHERE SHIP IN (SELECT NAME FROM SHIPS WHERE CLASS = 'Kongo')

SELECT CLASS
FROM CLASSES c
WHERE NUMGUNS >= ALL(SELECT NUMGUNS FROM CLASSES WHERE BORE = c.BORE)

SELECT NAME
FROM SHIPS
WHERE CLASS IN (
	SELECT CLASS
	FROM CLASSES c
	WHERE NUMGUNS >= ALL(SELECT NUMGUNS FROM CLASSES WHERE BORE = c.BORE)
)