--Problem 1

SELECT CASE 
		WHEN YEAR(BIRTHDATE) < 1960 THEN '50s and before'
		WHEN YEAR(BIRTHDATE) < 1970 THEN '60s'
		WHEN YEAR(BIRTHDATE) < 1980 THEN '70s'
		ELSE '80s and after'
	END AS 'Period', COUNT(*) AS COUNT
FROM MOVIESTAR
GROUP BY CASE 
		WHEN YEAR(BIRTHDATE) < 1960 THEN '50s and before'
		WHEN YEAR(BIRTHDATE) < 1970 THEN '60s'
		WHEN YEAR(BIRTHDATE) < 1980 THEN '70s'
		ELSE '80s and after'
	END

--Problem 2

SELECT BATTLE
FROM OUTCOMES
JOIN SHIPS s ON SHIP = NAME
JOIN CLASSES c ON c.CLASS = s.CLASS
WHERE NUMGUNS < 9
GROUP BY BATTLE
HAVING COUNT(SHIP) >= 3
	AND SUM(CASE WHEN RESULT = 'ok' THEN 1 ELSE 0 END) >= 2